// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvvmProdactApp.DataContext;

namespace MvvmProdactApp.Migrations
{
    [DbContext(typeof(StoredObjects))]
    [Migration("20200421162504_PP")]
    partial class PP
    {
    }
}
