// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvvmProdactApp.DataContext;

namespace MvvmProdactApp.Migrations
{
    [DbContext(typeof(StoredObjects))]
    [Migration("20200417080858_RRR")]
    partial class RRR
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
